version: 0.0
os: linux
files:
  - source: /
    destination: /home/nodejs
hooks:
  AfterInstall:
    - location: mongo_install
      runas: root
  ApplicationStart:
    - location: after_install_script.sh
      runas: root
